"""
Django settings for xin_show project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
# from celery import Celery

# celery = Celery(broker='redis://localhost:6379/0')

# celery.conf.update(
#     CELERY_DEFAULT_QUEUE = "myapp",
#     CELERY_DEFAULT_EXCHANGE = "myapp",
#     CELERY_DEFAULT_EXCHANGE_TYPE = "direct",
#     CELERY_DEFAULT_ROUTING_KEY = "myapp",
# )

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__))).replace('\\', '/')
TEMPLATES_PATH = os.path.join(BASE_DIR, 'templates')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'gie*=h8-$p$dzv+2ie*l&3=wx&i5zhh922j^p&8#5=m3xhn+*k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'kombu.transport.django',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'z_FileShow',
    'z_ReFile',
    '_models'
)


MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'xin_show.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_PATH],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'xin_show.wsgi.application'



# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
# import codecs
DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'Shake',
            'HOST': '123.57.226.182',
            'USER': 'root',
            'PASSWORD': 'Jksd3344',
            'PORT': '3306',
        },
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
STATIC_PATH=os.path.join(BASE_DIR,'static')
STATIC_URL = '/static/'
STATICFILES_DIRS=(
    STATIC_PATH,
)

SITE_ROOT=os.path.join(os.path.abspath(os.path.dirname(__file__)))
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'formatters': {
#         'standardTime': {
#                 'format': '%(asctime)s %(levelname)s %(module)s.%(funcName)s Line:%(lineno)d%(message)s'
#                 },
#         'standardFile': {
#                 'format': '%(levelname)s %(asctime)s %(message)s'
#                 },
#         "ingestion":{
#                 "format": "%(asctime)s %(message)s"
#         }
#     },
#     'handlers': {
#         'file': {
#             'level': 'INFO',
#             'class': 'logging.handlers.RotatingFileHandler',
#             'filename': os.path.join(SITE_ROOT,'log.log'),
#             'maxBytes':1024*1024*5,
#             'backupCount': 5,
#             'formatter':'standardFile',
#         },
#         'console':{            
#             'level':'DEBUG',            
#             'class':'logging.StreamHandler',        
#         },
#         "ingestion_log_file": {
#             'level': 'INFO',
#             'class': 'logging.handlers.RotatingFileHandler',
#             'filename': os.path.join(SITE_ROOT,'ingestion_log.log'),
#             'maxBytes':1024*1024*5,
#             'backupCount': 5,
#             'formatter':'ingestion',
#         }
#     },
#     'loggers': {
#         'all_project': {
#             'handlers': ['file'],
#             'level': 'INFO',
#             'propagate': True,
#         },
#         'ingestion_log': {
#             'handlers': ['ingestion_log_file'],
#             'level': 'INFO',
#             'propagate': True,
#         },
#         'django.db.backends': {
#             'handlers': ['console'],
#             'propagate': True,
#             'level':'DEBUG',
#         },
#     }
# }